services:
  - type: web
    name: tar-beta
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=$PORT wsgi:application
    envVars:
      - key: PORT
        value: 10000
      - key: TAR_WORKBOOK_PATH
        value: ./Cópia de TAR.xlsx
      - key: TAR_ACTIVITY_WORKBOOK_PATH
        value: ./Atividade Total TAR c radionuclideos.xls
      - key: TAR_TOTAL_ACTIVITY_WORKBOOK_PATH
        value: ./Dados Atividade TAR - Jayme (1).xlsx
      - key: TAR_ARTICLE_PATH
        value: ./Artigo TAR1 correção.pdf
